version: '3.7'
x-default: &default
  restart: unless-stopped
  networks:
    - influxdb-net

x-telegraf: &telegraf
  << : *default
  depends_on:
    - influxdb
  image: "telegraf:${TELEGRAF_VERSION?err}-alpine"
  
services:
  nginx:
    << : *default
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - '80:80'
      - '443:443'
    cap_add:
      - NET_ADMIN
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Canberra"
      URL: "${DOMAIN?err}"
      SUBDOMAINS: "grafana,influxdb"
      VALIDATION: "http"
      EMAIL: "${LETSENCRYPT_ACCOUNT_EMAIL}"
      # STAGING=true
    volumes:
      - ./nginx/proxy-confs:/config/nginx/proxy-confs
      - /srv:/config/www
      
  influxdb:
    << : *default
    container_name: inflxudb
    image: influxdb:${INFLUXDB_VERSION?err}-alpine
    ports:
      - '8086:8086'
    volumes: 
      - influxdb-storage:/var/lib/influxdb:rw
    environment:  
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "${INFLUXDB_ADMIN_USER?err}"
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD?err}"
      INFLUXDB_LOGGING_LEVEL: "warn"
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "true"
      INFLUXDB_HTTP_LOG_ENABLED: "true"
  grafana:
    << : *default
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION?err}
    depends_on:
      - influxdb
      - smtp
    ports:
      - '3000'
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Anon Org"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_SECURITY_ADMIN_USER: "${GRAFANA_ADMIN_USER?err}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD?err}"
      GF_DEFAULT_INSTANCE_NAME: "grafana.${DOMAIN?err}"
      GF_SERVER_DOMAIN: "grafana.${DOMAIN?err}"
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp:25"
      GF_SMTP_SKIP_VERIFY: "true"
      GF_SMTP_FROM_ADDRESS: "no-reply@grafana.${DOMAIN?err}"
      GF_INSTALL_PLUGINS: "raintank-worldping-app,ryantxu-ajax-panel,fetzerch-sunandmoon-datasource,andig-darksky-datasource"
      TZ: Australia/Canberra
  smtp:
    << : *default
    image: namshi/smtp
    container_name: smtp
    environment:
      - MAILNAME=${DOMAIN?err}
  telegraf-ttn:
    << : *telegraf
    container_name: telegraf-ttn
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_DATABASE: ${TELEGRAF_TTN_INFLUXDB_DB:-ttn}
      INFLUXDB_USER: "${TELEGRAF_TTN_INFLUXDB_USER?err}"
      INFLUXDB_PASSWORD: "${TELEGRAF_TTN_INFLUXDB_PASSWORD?err}"
      TTN_MESHED_APP_NAME: ${TELEGRAF_TTN_MESHED_APP_NAME?err}
      TTN_MESHED_PASSWORD: ${TELEGRAF_TTN_MESHED_PASSWORD?err}
    volumes: 
      - ./telegraf/telegraf-ttn.conf:/etc/telegraf/telegraf.conf:ro
  telegraf-public:
    << : *telegraf
    container_name: telegraf-public
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_DATABASE: public
      INFLUXDB_USER: "${INFLUXDB_PUBLIC_USER?err}"
      INFLUXDB_PASSWORD: "${INFLUXDB_PUBLIC_PASSWORD?err}"
      DATAACTTOKEN: "${TELEGRAF_DATAACTTOKEN}"
    volumes: 
      - ./telegraf/telegraf-public.conf:/etc/telegraf/telegraf.conf:ro
volumes:
  grafana-storage: 
  influxdb-storage:
networks:
  influxdb-net: {}