version: '3.7'
services:
  nginx:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    networks:
      - influxdb-net
    ports:
      - '80:80'
      - '443:443'
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Canberra
      - URL=${DOMAIN?err}
      - SUBDOMAINS=grafana,influxdb
      - VALIDATION=http
      - EMAIL=${LETSENCRYPT_ACCOUNT_EMAIL}
      # - STAGING=true
    volumes:
      - ./nginx/proxy-confs:/config/nginx/proxy-confs
      - /srv:/config/www

  influxdb:
    container_name: inflxudb
    image: influxdb:${INFLUXDB_VERSION?err}-alpine
    restart: unless-stopped
    networks:
      - influxdb-net
    ports:
      - '8086:8086'
    volumes: 
      - influxdb-storage:/var/lib/influxdb:rw
    environment:  
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER?err}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD?err}
      - INFLUXDB_LOGGING_LEVEL=warn
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=true
      - INFLUXDB_HTTP_LOG_ENABLED=true
  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION?err}
    depends_on:
      - influxdb
      - smtp
    restart: unless-stopped
    networks:
      - influxdb-net
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER?err}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD?err}
      - GF_DEFAULT_INSTANCE_NAME=grafana.${DOMAIN?err}
      - GF_SERVER_DOMAIN=grafana.${DOMAIN?err}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp:25
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=no-reply@grafana.${DOMAIN?err}
      - GF_INSTALL_PLUGINS=raintank-worldping-app,ryantxu-ajax-panel,fetzerch-sunandmoon-datasource,andig-darksky-datasource
  smtp:
    image: namshi/smtp
    container_name: smtp
    restart: unless-stopped
    environment:
      - MAILNAME=${DOMAIN?err}
    networks: 
      - influxdb-net
  telegraf:
    container_name: telegraf-ttn
    image: telegraf:${TELEGRAF_VERSION?err}-alpine
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - influxdb-net
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_DATABASE: ${TELEGRAF_TTN_INFLUXDB_DB:-ttn}
      INFLUXDB_USER: "${TELEGRAF_TTN_INFLUXDB_USER?err}"
      INFLUXDB_PASSWORD: "${TELEGRAF_TTN_INFLUXDB_PASSWORD?err}"
      TTN_MESHED_APP_NAME: ${TELEGRAF_TTN_MESHED_APP_NAME?err}
      TTN_MESHED_PASSWORD: ${TELEGRAF_TTN_MESHED_PASSWORD?err}
      TZ: Australia/Canberra
    volumes: 
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

volumes:
  grafana-storage: 
  influxdb-storage:
networks:
  influxdb-net: {}